# Generated by Django 2.2.24 on 2021-11-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Psot',
            new_name='Post',
        ),
    ]