# Generated by Django 2.2.24 on 2021-11-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_auto_20211106_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(default='000', max_length=20),
        ),
    ]