# Generated by Django 3.2.9 on 2021-11-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0007_auto_20211116_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_tag',
            field=models.ManyToManyField(to='sns.Tag'),
        ),
    ]
