# Generated by Django 3.2.9 on 2021-11-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0008_auto_20211117_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_tag',
        ),
    ]
