# Generated by Django 3.2.9 on 2021-11-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0010_post_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
