# Generated by Django 3.2.9 on 2021-11-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0007_auto_20211124_1019'),
        ('sns', '0011_post_post_image'),
    ]

    operations = [
    ]
