# Generated by Django 3.2.9 on 2021-11-29 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0013_auto_20211129_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='post_date',
            new_name='q_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='post_image',
            new_name='q_image',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='caption',
            new_name='text',
        ),
    ]
