# Generated by Django 3.2.9 on 2021-11-30 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0014_auto_20211129_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_follow', to='sns.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_follow', to='sns.account')),
            ],
        ),
    ]
