# Generated by Django 3.2.9 on 2021-11-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0015_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_good',
            field=models.ManyToManyField(blank=True, related_name='good_question', to='sns.Account'),
        ),
    ]
