# Generated by Django 3.2.9 on 2021-12-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0017_alter_question_q_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_good',
            field=models.ManyToManyField(blank=True, related_name='good_question', to='sns.Account'),
        ),
    ]
