# Generated by Django 3.2.9 on 2021-12-02 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0018_alter_question_q_good'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無し', max_length=20)),
                ('text', models.TextField(max_length=200)),
                ('a_image', models.ImageField(blank=True, upload_to='images')),
                ('a_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.account')),
            ],
        ),
    ]
