# Generated by Django 3.2.9 on 2021-12-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0019_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='a_good',
            field=models.ManyToManyField(blank=True, related_name='good_answer', to='sns.Account'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
