# Generated by Django 3.2.9 on 2021-12-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0020_auto_20211202_1600'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('owner', 'follow_target'), name='follow_unique'),
        ),
    ]
