# Generated by Django 3.2.9 on 2021-12-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0021_follow_follow_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='following',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_image',
            field=models.ImageField(blank=True, default='images/001-002.JPG', upload_to='images'),
        ),
    ]
