# Generated by Django 3.2.9 on 2021-12-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0022_auto_20211207_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='account',
            name='intro',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='q_tag',
            field=models.ManyToManyField(blank=True, to='sns.Q_Tag'),
        ),
    ]
