# Generated by Django 3.2.9 on 2021-12-13 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0013_auto_20211204_1538'),
        ('sns', '0024_auto_20211213_1058'),
    ]

    operations = [
    ]
