# Generated by Django 3.2.9 on 2021-12-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0026_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
